  notifier:
    build: ./notifier
    environment:
      MSGTELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      MSGTELEGRAM_CHATIDS: ${TELEGRAM_CHATIDS} # comma-separated, if more than one
      POSTGRESQL_DB: ${POSTGRES_DB:-zammad_production}
      POSTGRESQL_USER: ${POSTGRES_USER:-zammad}
      POSTGRESQL_PASS: ${POSTGRES_PASS:-zammad}
      POSTGRESQL_HOST: ${POSTGRES_HOST:-zammad-postgresql}
      MSGWEBHOOK_URL: ${WEBHOOK_URL}
      PYTHONUNBUFFERED: 1
    depends_on:
      - zammad-postgresql
